import { ArrowRight, Check, ChevronDown, Menu, Phone, Quote, Sparkles } from "lucide-react";

const services=[
  ["01","Revêtements de sols","Sols souples, résine, parquet, carrelage et solutions techniques adaptées à chaque usage."],
  ["02","Peinture & décoration","Des couleurs, matières et finitions qui transforment durablement vos espaces."],
  ["03","Chape fluide & carrelage","Une préparation précise et une pose maîtrisée pour un résultat impeccable."],
];

export default function Home(){return <main>
  <header><a className="logo" href="#accueil"><img src="/logo.png" alt="Beattie Sols"/></a><nav><a href="#expertises">Expertises</a><a href="#realisations">Réalisations</a><a href="#entreprise">L’entreprise</a></nav><a className="nav-cta" href="https://beattiesols.com/devis">Demander un devis <ArrowRight size={16}/></a><button className="menu" aria-label="Menu"><Menu/></button></header>
  <section className="hero" id="accueil"><img src="/hero.jpg" alt="Chantier Beattie Sols"/><div className="shade"/><div className="hero-copy"><p className="eyebrow">Artisan du sol au plafond · Rennes &amp; Bretagne</p><h1>Vos espaces.<br/><em>Notre savoir-faire.</em></h1><p>Revêtements de sols techniques, peinture et décoration. Des réalisations soignées, pensées pour durer et vous ressembler.</p><div className="actions"><a className="btn light" href="https://beattiesols.com/devis">Parlons de votre projet <ArrowRight size={17}/></a><a className="under" href="#realisations">Voir nos réalisations</a></div></div><a href="#expertises" className="scroll"><span>Découvrir</span><ChevronDown size={17}/></a><div className="hero-badge"><strong>Depuis 2012</strong><span>Qualité à votre service</span></div></section>
  <section className="manifesto" id="entreprise"><p className="kicker">Beattie Sols</p><div><h2>La maîtrise technique.<br/>Le sens du <em>détail.</em></h2><p>Particuliers ou professionnels, nous vous accompagnons de la préparation des supports aux dernières finitions. Une équipe de compagnons qualifiés, un interlocuteur engagé et une exigence constante à chaque étape.</p><div className="facts"><span><strong>12+</strong> années d’expérience</span><span><strong>2</strong> pôles d’expertise</span><span><strong>100%</strong> sur mesure</span></div></div></section>
  <section className="expertises" id="expertises"><div className="section-title"><p className="kicker">Nos expertises</p><h2>Un seul partenaire.<br/>Toutes vos finitions.</h2></div><div className="service-list">{services.map(s=><a href="https://beattiesols.com/devis" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div><i><ArrowRight size={20}/></i></a>)}</div></section>
  <section className="projects" id="realisations"><div className="project tall"><img src="/project-1.jpg" alt="Réalisation de sol Beattie Sols"/><span>Revêtement de sol · Rennes</span></div><div className="project-copy"><p className="kicker pale">Nos réalisations</p><h2>Chaque chantier<br/>est une <em>signature.</em></h2><p>Des espaces professionnels aux intérieurs privés, découvrez des projets où technicité, précision et esthétique ne font qu’un.</p><a className="btn blue" href="https://beattiesols.com/nos-realisations">Explorer nos projets <ArrowRight size={17}/></a></div><div className="project wide"><img src="/project-2.jpg" alt="Projet peinture et sols Beattie Sols"/><span>Agencement professionnel · Bretagne</span></div></section>
  <section className="values"><div><Sparkles/><h3>Conseil sur mesure</h3><p>Une solution adaptée à vos usages, votre style et votre budget.</p></div><div><Check/><h3>Compagnons qualifiés</h3><p>Un savoir-faire éprouvé et une exécution attentive aux détails.</p></div><div><Quote/><h3>Engagement tenu</h3><p>Des échanges clairs, un chantier suivi et le respect de nos engagements.</p></div></section>
  <section className="about"><div><p className="kicker">Pourquoi nous choisir</p><h2>La qualité n’est pas<br/>une option.</h2></div><p>Depuis 2012, Beattie Sols intervient à Rennes et partout en Bretagne pour transformer les lieux de vie et de travail. Nous sélectionnons les bons matériaux, maîtrisons les contraintes techniques et soignons chaque finition pour livrer un résultat à la hauteur de votre projet.</p></section>
  <section className="contact"><div><p className="kicker pale">Un projet en tête ?</p><h2>Construisons-le<br/><em>ensemble.</em></h2></div><div><p>Décrivez-nous votre besoin. Nous vous répondons avec des conseils concrets et un devis gratuit.</p><a className="btn light" href="https://beattiesols.com/devis">Obtenir mon devis <ArrowRight size={17}/></a><a className="tel" href="tel:0622285476"><Phone size={16}/> 06 22 28 54 76</a></div></section>
  <footer><img src="/logo.png" alt="Beattie Sols"/><p>3 route de Melesse · 35520 La Mézière</p><p>© 2026 Beattie Sols</p></footer>
  </main>}
